language: node_js
node_js:
  - '8'
  - '10'
  - '12'
cache:
  directories:
    - 'node_modules'
before_install:
  - npm i -g npm@latest
script:
  - npm run lint
  - npm run test:coverage
after_success:
  - npm run report-coverage